# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

language: generic # optional, just removes the language badge

services:
  - docker

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - ROS_REPO=ros
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - AFTER_SETUP_UPSTREAM_WORKSPACE='apt-get install -y wget && wget https://raw.githubusercontent.com/clearpathrobotics/public-rosdistro/master/rosdep/50-clearpath.list -O /etc/ros/rosdep/sources.list.d/50-clearpath.list  && rosdep update'
  matrix: # each line is a job
    - ROS_DISTRO="melodic"

# clone and run industrial_ci
install:
  - wget https://packages.clearpathrobotics.com/public.key -O - | sudo apt-key add -
  - sudo sh -c 'echo "deb https://packages.clearpathrobotics.com/stable/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/clearpath-latest.list'
  - sudo apt-get update
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
